<?php

return [
    'business' => [
        'name' => 'Laboratorio Biologico BIOLAB',
        'address' => 'Entrada Principal Aldea Chocola, San Pablo Jocopilas, Suchitepequez',
        'phone' => '4171-6435',
        'director' => 'Enna Guisela Merlos Rodas',
        'credential' => 'Quimico Biologo - Colegiado 4571',
    ],

    'referrers' => [
        'DR. SUHUL',
        'DR. GARCIA',
        'DR. MENCHU',
        'DR. DUBON',
        'DRA. CONTRERAS',
        'DRA. ESTRADA',
        'CENTRO DE SALUD',
        'FARMACIA SHADAY',
        'PRESENTE',
        'DR. IXCOT',
        'DRA. MANSILLA',
    ],

    'categories' => [
        [
            'slug' => 'hematologia',
            'name' => 'Hematologia',
            'title' => 'Hematologia completa',
            'tests' => [
                ['name' => 'RECUENTO DE GLOBULOS BLANCOS', 'unit' => 'Cel/mm3', 'reference' => '5000-10000'],
                ['name' => 'RECUENTO DE GLOBULOS ROJOS', 'unit' => 'mil/mm3', 'reference' => '3.80-5.60'],
                ['name' => 'HEMOGLOBINA', 'unit' => 'g/dL', 'reference' => '12.0-17.0'],
                ['name' => 'HEMATOCRITO', 'unit' => '%', 'reference' => '36-52'],
                ['name' => 'PLAQUETAS', 'unit' => 'Cel/mm3', 'reference' => '150000-450000'],
                ['name' => 'FORMULA DIFERENCIAL', 'unit' => '', 'reference' => ''],
            ],
        ],
        [
            'slug' => 'orina',
            'name' => 'Orina',
            'title' => 'Uroanalisis',
            'tests' => [
                ['name' => 'EXAMEN FISICO', 'unit' => '', 'reference' => ''],
                ['name' => 'COLOR', 'unit' => '', 'reference' => 'Amarillo'],
                ['name' => 'ASPECTO', 'unit' => '', 'reference' => 'Claro'],
                ['name' => 'DENSIDAD', 'unit' => '', 'reference' => '1.005-1.030'],
                ['name' => 'pH', 'unit' => '', 'reference' => '5.0-8.0'],
                ['name' => 'EXAMEN QUIMICO', 'unit' => '', 'reference' => ''],
                ['name' => 'LEUCOCITOS', 'unit' => 'mg/dl', 'reference' => 'Negativo'],
                ['name' => 'NITRITOS', 'unit' => '', 'reference' => ''],
                ['name' => 'PROTEINAS', 'unit' => '', 'reference' => 'Negativo'],
                ['name' => 'GLUCOSA', 'unit' => '', 'reference' => ''],
                ['name' => 'CETONAS', 'unit' => 'mg/dl', 'reference' => ''],
                ['name' => 'BILIRRUBINAS', 'unit' => 'mg/dl', 'reference' => ''],
                ['name' => 'UROBILINOGENO', 'unit' => 'mg/dl', 'reference' => ''],
                ['name' => 'SANGRE', 'unit' => 'Ery/ul', 'reference' => ''],
                ['name' => 'HEMOGLOBINA', 'unit' => 'Ery/ul', 'reference' => ''],
                ['name' => 'EXAMEN MICROSCOPICO', 'unit' => '', 'reference' => ''],
                ['name' => 'CELULAS EPITELIALES', 'unit' => '', 'reference' => ''],
                ['name' => 'LEUCOCITOS', 'unit' => '', 'reference' => '0-4'],
                ['name' => 'ERITROCITOS', 'unit' => '', 'reference' => '0-3'],
                ['name' => 'BACTERIAS', 'unit' => '', 'reference' => ''],
                ['name' => 'LEVADURAS', 'unit' => '', 'reference' => ''],
                ['name' => 'MICELIO', 'unit' => '', 'reference' => ''],
                ['name' => 'CRISTALES', 'unit' => '', 'reference' => ''],
                ['name' => 'CILINDROS', 'unit' => '', 'reference' => ''],
                ['name' => 'OTROS', 'unit' => '', 'reference' => ''],
            ],
        ],
        [
            'slug' => 'heces',
            'name' => 'Heces',
            'title' => 'Examen de heces',
            'tests' => [
                ['name' => 'EXAMEN MACROSCOPICO', 'unit' => '', 'reference' => ''],
                ['name' => 'COLOR', 'unit' => '', 'reference' => 'Cafe'],
                ['name' => 'CONSISTENCIA', 'unit' => '', 'reference' => 'Blanda'],
                ['name' => 'EXAMEN MICROSCOPICO', 'unit' => '', 'reference' => ''],
                ['name' => 'MOCO', 'unit' => '', 'reference' => 'Negativo'],
                ['name' => 'SANGRE OCULTA', 'unit' => '', 'reference' => 'Negativo'],
                ['name' => 'PARASITOS', 'unit' => '', 'reference' => ''],
                ['name' => 'HUEVOS', 'unit' => '', 'reference' => ''],
                ['name' => 'QUISTES', 'unit' => '', 'reference' => ''],
                ['name' => 'TROFOZOITOS', 'unit' => '', 'reference' => ''],
                ['name' => 'OTROS:', 'unit' => '', 'reference' => ''],
            ],
        ],
        [
            'slug' => 'lipidos',
            'name' => 'Lipidos',
            'title' => 'Perfil de lipidos',
            'tests' => [
                ['name' => 'Colesterol total', 'unit' => 'mg/dL', 'reference' => '< 200'],
                ['name' => 'Trigliceridos', 'unit' => 'mg/dL', 'reference' => '< 150'],
                ['name' => 'HDL colesterol', 'unit' => 'mg/dL', 'reference' => '> 40'],
                ['name' => 'LDL colesterol', 'unit' => 'mg/dL', 'reference' => '< 100'],
            ],
        ],
        [
            'slug' => 'renales',
            'name' => 'Renales',
            'title' => 'Pruebas renales',
            'tests' => [
                ['name' => 'Glucosa', 'unit' => 'mg/dL', 'reference' => '70-110'],
                ['name' => 'Urea', 'unit' => 'mg/dL', 'reference' => '10-50'],
                ['name' => 'Creatinina', 'unit' => 'mg/dL', 'reference' => '0.6-1.3'],
                ['name' => 'Acido urico', 'unit' => 'mg/dL', 'reference' => '2.5-7.0'],
            ],
        ],
        [
            'slug' => 'hepaticas',
            'name' => 'Hepaticas',
            'title' => 'Pruebas hepaticas',
            'tests' => [
                ['name' => 'TGO/AST', 'unit' => 'U/L', 'reference' => '0-40'],
                ['name' => 'TGP/ALT', 'unit' => 'U/L', 'reference' => '0-40'],
                ['name' => 'Bilirrubina total', 'unit' => 'mg/dL', 'reference' => '0.2-1.2'],
                ['name' => 'Fosfatasa alcalina', 'unit' => 'U/L', 'reference' => '40-129'],
            ],
        ],
        ['slug' => 'serologia', 'name' => 'Serologia', 'title' => 'Serologia', 'tests' => []],
        ['slug' => 'hormonas', 'name' => 'Hormonas', 'title' => 'Hormonas', 'tests' => []],
        ['slug' => 'coagulacion', 'name' => 'Coagulacion', 'title' => 'Coagulacion', 'tests' => []],
        ['slug' => 'bacterologia', 'name' => 'Bacteriologia', 'title' => 'Bacteriologia', 'tests' => []],
        ['slug' => 'micologia', 'name' => 'Micologia', 'title' => 'Micologia', 'tests' => []],
        ['slug' => 'inmunoglobina', 'name' => 'Inmunoglobulinas', 'title' => 'Inmunoglobulinas', 'tests' => []],
        ['slug' => 'enfermedades-infecciosas', 'name' => 'Enfermedades infecciosas', 'title' => 'Enfermedades infecciosas', 'tests' => []],
        ['slug' => 'inmunohematologia', 'name' => 'Inmunohematologia', 'title' => 'Inmunohematologia', 'tests' => []],
        ['slug' => 'metabolismo', 'name' => 'Metabolismo', 'title' => 'Metabolismo', 'tests' => []],
        ['slug' => 'pancreaticas', 'name' => 'Pancreaticas', 'title' => 'Pancreaticas', 'tests' => []],
        ['slug' => 'cardiacas', 'name' => 'Cardiacas', 'title' => 'Cardiacas', 'tests' => []],
        ['slug' => 'prostatica', 'name' => 'Prostaticas', 'title' => 'Prostaticas', 'tests' => []],
        ['slug' => 'electrolitos', 'name' => 'Electrolitos', 'title' => 'Electrolitos', 'tests' => []],
        ['slug' => 'marcadores-tumorales', 'name' => 'Marcadores tumorales', 'title' => 'Marcadores tumorales', 'tests' => []],
        ['slug' => 'otros', 'name' => 'Otros', 'title' => 'Otros analisis', 'tests' => []],
    ],
];
